name: paisa_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.7.0
  google_fonts: ^6.2.1
  http: ^1.4.0
  flutter_launcher_icons: ^0.14.3
  markdown_widget: ^2.3.2+8
  flutter_background_service: ^5.1.0
  permission_handler: ^12.0.0+1
  provider: ^6.1.2
  readsms:
    git:
      url: https://github.com/Ali3Jamous/readsms_plugin.git
      ref: fix-namespace-agp8 # branch name
  flutter_local_notifications: ^19.2.1
  flutter_logs: ^2.2.1
  speech_to_text: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
