name: paisa_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.7.0
  google_fonts: ^6.2.1
  http: ^1.3.0
  flutter_launcher_icons: ^0.14.3
  markdown_widget: ^2.3.2+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
